### ISSUE TITLE
Tests failing with incorrect timestamps on node 0.12+

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-contrib-copy#269] opened 2016-02-01 17:30 UTC
```
Running "nodeunit:tests" (nodeunit) task
Testing copy_test.js.......F
>> copy - timestamp
>> Error: 1454343979000 == 1454343979444
>> at Object.exports.copy.timestamp (test/copy_test.js:83:10)
>> copy - timestamp
>> Error: 1454343979000 == 1454343979444
>> at Object.exports.copy.timestamp (test/copy_test.js:84:10)

```

cc @shama

**Comment by shama** [comment] 2016-02-01 17:32
Duplicate of https://github.com/gruntjs/grunt-contrib-copy/issues/216

I looked into it and found the issue but haven't fixed it.

**Comment by vladikoff** [comment] 2016-02-01 17:33
:+1: oh ok, i lost the context on this one

**Closed by shama** 2016-02-01 17:32 UTC
